language: go
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

jobs:
  include:
    - stage: "build and push docker image"
      script: |
        #! /bin/bash -eu
        docker --version
        docker build -t wahyd4/aria2-ui:3.0.${TRAVIS_BUILD_NUMBER} .
        if [ "${TRAVIS_BRANCH}" = "master" ]; then
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag wahyd4/aria2-ui:3.0.$TRAVIS_BUILD_NUMBER wahyd4/aria2-ui:latest
          docker push wahyd4/aria2-ui:3.0.$TRAVIS_BUILD_NUMBER
          docker push wahyd4/aria2-ui:latest
        fi
